# Generated by Django 2.2.1 on 2019-09-16 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activity_title',
            new_name='weekly_goal',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom',
            new_name='Classroom',
        ),
        migrations.RenameField(
            model_name='lesson_school_info',
            old_name='teacher',
            new_name='planning_teacher',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='blooms',
        ),
        migrations.RemoveField(
            model_name='assessments',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='teacher',
        ),
        migrations.AddField(
            model_name='activities',
            name='bl',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='mi1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='mi2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='mi3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessments',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.classroom'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student', to='schoolio.student_profiles'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.subjects'),
        ),
        migrations.AddField(
            model_name='standards',
            name='grade_level',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_profiles',
            name='grade_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='wrap_up',
            field=models.CharField(max_length=500, verbose_name='Essential Questions'),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.activities'),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='group_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='hu_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='independent_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='kinesthetic_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='linguistic_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='logical_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='lu_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='mu_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='musical_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='naturalist_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='visual_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='standards',
            name='objective',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='standards',
            name='skill_topic',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='standards',
            name='standard',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='standards',
            name='subject',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
                ('day', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.classroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='create_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_title', models.TextField(max_length=150)),
                ('update', models.TextField(max_length=1000)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.school')),
            ],
        ),
    ]
