# Generated by Django 2.2.1 on 2019-09-18 03:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='assessment_mark',
        ),
        migrations.AddField(
            model_name='assessments',
            name='assessment_total',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='student_assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_mark', models.IntegerField()),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.assessments')),
                ('student', models.ManyToManyField(blank=True, to='schoolio.student_profiles')),
            ],
        ),
    ]
