# Generated by Django 2.2.1 on 2019-09-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_school_info',
            old_name='teacher',
            new_name='planning_teacher',
        ),
    ]
