# Generated by Django 2.2.1 on 2019-09-21 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherschedule',
            old_name='day',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='teacherschedule',
            old_name='location',
            new_name='monday',
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.school'),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='thursday',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='tuesday',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='wednesday',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
