# Generated by Django 2.2.1 on 2019-09-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_assessment',
            name='student',
        ),
        migrations.AddField(
            model_name='student_assessment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.student_profiles'),
        ),
    ]
