# Generated by Django 2.2.1 on 2019-09-26 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_school_info',
            name='classroom',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson_school_info',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson_school_info',
            name='schedule',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson_school_info',
            name='school',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
