# Generated by Django 2.2.1 on 2019-09-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0002_auto_20190926_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='activity',
        ),
    ]
