# Generated by Django 2.2.1 on 2019-09-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0002_auto_20190921_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherschedule',
            name='period',
        ),
    ]
