# Generated by Django 2.2.1 on 2019-09-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0002_auto_20190904_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userthread',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='userthread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='UserThread',
        ),
    ]
