# Generated by Django 2.2.1 on 2019-09-11 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0002_auto_20190910_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='blooms',
        ),
        migrations.AddField(
            model_name='activities',
            name='bl',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='mi1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='mi2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='mi3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='group_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='hu_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='independent_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='kinesthetic_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='linguistic_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='logical_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='lu_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='mu_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='musical_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='naturalist_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='visual_level',
            field=models.IntegerField(),
        ),
    ]
