# Generated by Django 2.2.1 on 2019-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0002_auto_20190918_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='student_profiles',
            name='d_o_b',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_profiles',
            name='student_id',
            field=models.CharField(blank=True, default=-123, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='school_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
