# Generated by Django 2.2.1 on 2019-09-18 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0003_auto_20190918_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profiles',
            name='user',
        ),
        migrations.AddField(
            model_name='student_profiles',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_profiles',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_profiles',
            name='student_ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
