# Generated by Django 2.2.1 on 2019-09-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0003_remove_assessments_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='lu_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='lu_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='lu_med',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_assessment',
            name='understanding_level',
            field=models.IntegerField(default=0),
        ),
    ]
