# Generated by Django 2.2.1 on 2019-09-21 18:14

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0003_remove_teacherschedule_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_url',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='Classroom'),
            preserve_default=False,
        ),
    ]
