# Generated by Django 2.2.1 on 2019-09-07 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0003_auto_20190904_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
