# Generated by Django 2.2.1 on 2019-09-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0003_auto_20190911_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activity_title',
            new_name='weekly_goal',
        ),
    ]
