# Generated by Django 2.2.1 on 2019-09-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0004_auto_20190918_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profiles',
            name='student_id',
        ),
    ]
