# Generated by Django 2.2.1 on 2019-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0004_auto_20190911_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='hu_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='lu_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom_subject_summary',
            name='mu_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
