# Generated by Django 2.2.1 on 2019-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0004_auto_20190927_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assessment',
            name='assessment_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_assessment',
            name='assessment_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_assessment',
            name='understanding_level',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
