# Generated by Django 2.2.1 on 2019-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0004_classroom_class_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_url',
            field=models.CharField(max_length=30),
        ),
    ]
