# Generated by Django 2.2.1 on 2019-09-09 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0004_activities_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_school_info',
            name='teacher',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
