# Generated by Django 2.2.1 on 2019-09-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0005_auto_20190921_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_url',
        ),
    ]
