# Generated by Django 2.2.1 on 2019-09-19 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0005_remove_student_profiles_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_school_info',
            name='grade',
        ),
        migrations.AddField(
            model_name='lesson_school_info',
            name='grade_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
