# Generated by Django 2.2.1 on 2019-09-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0006_auto_20190919_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_school_info',
            name='grade_level',
        ),
    ]
