# Generated by Django 2.2.1 on 2019-09-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0006_create_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_update',
            new_name='create_updates',
        ),
    ]
