# Generated by Django 2.2.1 on 2019-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0007_auto_20190913_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='wrap_up',
            field=models.CharField(max_length=500, verbose_name='Essential Questions'),
        ),
    ]
