# Generated by Django 2.2.1 on 2019-09-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0007_auto_20190922_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_school_info',
            name='days',
        ),
    ]
