# Generated by Django 2.2.1 on 2019-09-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0007_remove_lesson_school_info_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='assessment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='classroom_averages',
            name='lu_high',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classroom_averages',
            name='lu_low',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classroom_averages',
            name='lu_med',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classroom_averages',
            name='mi_one',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classroom_averages',
            name='mi_three',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classroom_averages',
            name='mi_two',
            field=models.CharField(max_length=30),
        ),
    ]
