# Generated by Django 2.2.1 on 2019-09-13 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0008_auto_20190913_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='standards',
            name='grade_level',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standards',
            name='objective',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='standards',
            name='skill_topic',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='standards',
            name='standard',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='standards',
            name='subject',
            field=models.TextField(max_length=500),
        ),
    ]
