# Generated by Django 2.2.1 on 2019-09-24 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0009_auto_20190924_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='period',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
