# Generated by Django 2.2.1 on 2019-09-13 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0009_auto_20190913_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_period',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
