# Generated by Django 2.2.1 on 2019-09-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0010_activities_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_subject_summary',
            name='lesson_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.lesson_school_info'),
        ),
    ]
