# Generated by Django 2.2.1 on 2019-09-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0011_auto_20190914_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_period',
        ),
    ]
