# Generated by Django 2.2.1 on 2019-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0012_remove_classroom_class_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profiles',
            old_name='grade',
            new_name='grade_level',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='student_profiles',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='student', to='schoolio.student_profiles'),
        ),
    ]
