# Generated by Django 2.2.1 on 2019-09-15 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0013_auto_20190914_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='period',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
