# Generated by Django 2.2.1 on 2019-09-15 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0014_teacherschedule_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='Subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
