# Generated by Django 2.2.1 on 2019-09-15 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0015_auto_20190915_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='student',
        ),
        migrations.AddField(
            model_name='assessments',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.classroom'),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolio.activities'),
        ),
    ]
