# Generated by Django 2.2.1 on 2019-09-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0016_auto_20190915_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom',
            new_name='Classroom',
        ),
    ]
