# Generated by Django 2.2.1 on 2019-09-15 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0018_auto_20190915_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profiles',
            name='grade_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
