# Generated by Django 2.2.1 on 2019-09-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolio', '0019_auto_20190915_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student', to='schoolio.student_profiles'),
        ),
    ]
