# Generated by Django 2.2.1 on 2019-09-09 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='visitor')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('sender_archived', models.BooleanField(default=False, verbose_name='archived by sender')),
                ('recipient_archived', models.BooleanField(default=False, verbose_name='archived by recipient')),
                ('sender_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted by sender at')),
                ('recipient_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted by recipient at')),
                ('moderation_status', models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Rejected')], default='p', max_length=1, verbose_name='status')),
                ('moderation_date', models.DateTimeField(blank=True, null=True, verbose_name='moderated at')),
                ('moderation_reason', models.CharField(blank=True, max_length=120, verbose_name='rejection reason')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
