# Generated by Django 2.1.4 on 2019-04-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190326_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploads', verbose_name='Figure'),
        ),
    ]
