# Generated by Django 2.1.4 on 2019-05-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_follow_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
