# Generated by Django 2.1.4 on 2019-04-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='main', max_length=30),
        ),
    ]
